import { JSONHistory } from 'src/MTtoJSON';
import { findLongestStreaks, findBiggestProfitAndLoss } from '../../src/Calculations';

describe('findLongestStreaks', () => {
  it('should correctly calculate the longest winning and losing streaks', () => {
    const orders: JSONHistory = [
      {
        Platform: 'MT4',
        Transaction_Type: 'ORDER',
        Type: '',
        Order_ID: 0,
        Symbol: '',
        Volume: 0,
        Time: 0,
        Close_Time: 0,
        Order_Type: 'BUY',
        Open_Price: 0,
        Current_Price: 0,
        Profit: 10,
        Swap: 0,
        Commission: -1,
        Balance: 0,
        Comment: '',
        Magic: 0,
      },
      {
        Platform: 'MT4',
        Transaction_Type: 'ORDER',
        Type: '',
        Order_ID: 0,
        Symbol: '',
        Volume: 0,
        Time: 0,
        Close_Time: 0,
        Order_Type: 'BUY',
        Open_Price: 0,
        Current_Price: 0,
        Profit: 20,
        Swap: 0,
        Commission: -2,
        Balance: 0,
        Comment: '',
        Magic: 0,
      },
      {
        Platform: 'MT4',
        Transaction_Type: 'ORDER',
        Type: '',
        Order_ID: 0,
        Symbol: '',
        Volume: 0,
        Time: 0,
        Close_Time: 0,
        Order_Type: 'BUY',
        Open_Price: 0,
        Current_Price: 0,
        Profit: -30,
        Swap: 0,
        Commission: 3,
        Balance: 0,
        Comment: '',
        Magic: 0,
      },
      {
        Platform: 'MT4',
        Transaction_Type: 'ORDER',
        Type: '',
        Order_ID: 0,
        Symbol: '',
        Volume: 0,
        Time: 0,
        Close_Time: 0,
        Order_Type: 'BUY',
        Open_Price: 0,
        Current_Price: 0,
        Profit: -40,
        Swap: 0,
        Commission: 4,
        Balance: 0,
        Comment: '',
        Magic: 0,
      },
      {
        Platform: 'MT4',
        Transaction_Type: 'ORDER',
        Type: '',
        Order_ID: 0,
        Symbol: '',
        Volume: 0,
        Time: 0,
        Close_Time: 0,
        Order_Type: 'BUY',
        Open_Price: 0,
        Current_Price: 0,
        Profit: 50,
        Swap: 0,
        Commission: -5,
        Balance: 0,
        Comment: '',
        Magic: 0,
      },
    ];

    const result = findLongestStreaks(orders);

    expect(result).toEqual({
      longestWinningStreak: 2,
      longestLosingStreak: 2,
      winningStreakAmount: 27,
      losingStreakAmount: -63,
    });
  });
});

